### ISSUE TITLE
No repository license

### ISSUE THREAD

**Issue by katesuyu** [pepe/janet.kak#2] opened 2021-02-11 20:05 UTC
I would like to contribute to and/or fork this project to fix some flaws which prevent verbatim use in my dotfiles, but without a license I'm afraid I don't feel comfortable doing so.

If you want to be consistent with most Kakoune plugins, it's conventional to choose UNLICENSE. Alternatively, simply use MIT to be consistent with the Janet ecosystem.

**Comment by VarLad** [comment] 2021-02-12 07:09
@pepe 
My two cents🙂: 
I think this is the only kakoune configuration for janet. Since it doesn't work for me, I don't know the intended behaviour. 
But I suggest, you should actually try making a PR to https://github.com/mawww/kakoune/blob/master/rc/filetype/, and shift this project there!

**Comment by pepe** [comment] 2021-02-12 08:26
Thank you both. TBH I have never thought anyone would use this. Anyway I will add UNLICENSE at the weekend. 

I guess, because I am using Janet for generating keyword for the highlighting it cannot be part of the Kakoune rc. But it definitely could be done in two phases, so maybe later.

Anyway thank you, I will check back when I have time to add license.

**Comment by pepe** [comment] 2021-02-12 09:29
Fixed by 237843eb5cd7648e41af62451fe13ddfa93ce187

**Closed as completed** 2021-02-12 11:23 UTC
